package lib.input;

public enum InputAction {
    MOVE_UP,
    MOVE_DOWN,
    MOVE_LEFT,
    MOVE_RIGHT,
    THROTTLE_UP,
    THROTTLE_DOWN,
    THROTTLE_LEFT,
    THROTTLE_RIGHT,
    MENU_PREVIOUS,
    MENU_NEXT,
    MENU_CONFIRM,
    PAUSE,
    DIALOG_NEXT,
    CYCLE_COLOR,
    VOXEL_BUILD,
    VOXEL_DESTROY,
    JUMP,
    SHOOT,
    CYCLE_THROTTLE,
    TOGGLE_GOALS
}
